apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meta-image-generator
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - meta-image-generator.lb.djnd.si
      secretName: meta-image-generator-tls
  rules:
    - host: meta-image-generator.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meta-image-generator
                port:
                  number: 3000
