apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meta-image-generator
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: meta-image-generator
    newName: rg.fr-par.scw.cloud/djnd/meta-image-generator
    newTag: '281b4da9d555a1a9aa5fb3d1c4d4c1430e0211d0'
