apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meta-image-generator
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: meta-image-generator
    newName: rg.fr-par.scw.cloud/djnd/meta-image-generator
    newTag: 'c70dcd7631596c76738a662e627cabac5c3b635b'
